services:
  db:
    image: altasbatuhan/bookwise-database:v1.1
    container_name: project-db-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bookwise
    ports:
      - "5433:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    image: altasbatuhan/bookwise-backend:v1.2
    container_name: bookwise-backend-2
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/bookwise
    ports:
      - "5005:5005"
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    image: altasbatuhan/bookwise-frontend:v1.2
    container_name: bookwise-frontend-2
    ports:
      - "3000:80"
    networks:
      - backend_network
    depends_on:
      - backend

networks:
  backend_network:
    driver: bridge

volumes:
  project_postgres_data:
