version: "3.8"
services:
  db:
    image: altasbatuhan/bookwise-db:latest
    container_name: project-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bookwise
    ports:
      - "5433:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    image: altasbatuhan/bookwise-backend:latest
    container_name: bookwise-backend-1
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/bookwise
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    image: altasbatuhan/bookwise-frontend:latest
    container_name: bookwise-frontend-1
    ports:
      - "3000:80"
    networks:
      - backend_network
    depends_on:
      - backend

networks:
  backend_network:
    driver: bridge

volumes:
  project_postgres_data:
